[package]
name = "csv_to_json_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
serde = "1.0.217"
serde_json = "1.0.134"
