[package]
name = "publishCrate_14"
version = "0.1.0"
edition = "2021"
description = "A test lib"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
